# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol/protocol.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protocol/protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protocol/protocol.proto\x12\x04pftp\"-\n\x07GetFile\x12\x0f\n\x07unknown\x18\x01 \x02(\x08\x12\x11\n\tfile_name\x18\x02 \x02(\t\">\n\x0fPlatformVersion\x12\r\n\x05major\x18\x01 \x02(\x05\x12\r\n\x05minor\x18\x02 \x02(\x05\x12\r\n\x05patch\x18\x03 \x02(\x05\"<\n\rDeviceVersion\x12\r\n\x05major\x18\x01 \x02(\x05\x12\r\n\x05minor\x18\x02 \x02(\x05\x12\r\n\x05patch\x18\x03 \x02(\x05\"\x9c\x02\n\nDeviceInfo\x12\x11\n\tunknown_1\x18\x01 \x01(\x08\x12/\n\x10platform_version\x18\x02 \x02(\x0b\x32\x15.pftp.PlatformVersion\x12+\n\x0e\x64\x65vice_version\x18\x03 \x02(\x0b\x32\x13.pftp.DeviceVersion\x12\x11\n\tunknown_4\x18\x04 \x02(\x08\x12\x11\n\tunknown_5\x18\x05 \x01(\x08\x12\x11\n\tdevice_id\x18\x06 \x02(\t\x12\x12\n\nmodel_name\x18\x07 \x02(\t\x12\x11\n\tunknown_6\x18\x08 \x02(\t\x12\x15\n\rproduct_color\x18\t \x02(\t\x12\x13\n\x0bproduct_sex\x18\n \x02(\t\x12\x11\n\tsystem_id\x18\x0b \x02(\t\"&\n\x04\x46ile\x12\x10\n\x08unkown_1\x18\x01 \x02(\x08\x12\x0c\n\x04path\x18\x02 \x02(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol.protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETFILE']._serialized_start=33
  _globals['_GETFILE']._serialized_end=78
  _globals['_PLATFORMVERSION']._serialized_start=80
  _globals['_PLATFORMVERSION']._serialized_end=142
  _globals['_DEVICEVERSION']._serialized_start=144
  _globals['_DEVICEVERSION']._serialized_end=204
  _globals['_DEVICEINFO']._serialized_start=207
  _globals['_DEVICEINFO']._serialized_end=491
  _globals['_FILE']._serialized_start=493
  _globals['_FILE']._serialized_end=531
# @@protoc_insertion_point(module_scope)
